### ISSUE TITLE
Frequently and consistently dropped connections

### ISSUE THREAD

**Issue by SnareChops** [gammazero/nexus#205] opened 2019-10-16 21:15 UTC
I have exhausted all options other than posting here. Searched google over multiple months and have yet to come up with an explanation or solution to this issue.

I have a decent sized microservice stack all connected to a singular nexus router. Traffic is still low as I am in development. Connected to this stack are also a number of raspberry pi's (using the nexus client library, written in go), and a website connected with autobahn.js.

The issue I'm seeing is consistently dropping connections after about 30s - 1min. This is pretty much without fail. After that I have coded the applications to reconnect and they do successfully, but then proceed to drop again, and again, and again.

> This appears to only affect connections that are NOT running on the same machine. All connections are made with `ConnectNet` using the client library

I've been searching for a ping requirement or config option to see if this is user error on my part, and that the connections are being terminated by the router under the assumption that they have died. So far have found nothing in the documentation or wiki.

Does anyone have an idea what could be causing this and what I could do to solve this issue? I understand connections dropping occasionally, and applications should be built to handle this, but this is consistent and frequent. The longest I've ever seen a connection last before dropping is about 1.5min.

Is this user error? Is there a ping requirement? Link to a doc page?

Thank you and sorry for filing an issue, though I feel I've run out of options...

**Comment by gammazero** [comment] 2019-11-16 22:51
Sorry for the terribly long delay in responding, have been away for some time and will try to reproduce and fix the issue.  Things to check that occur to me are:

1) Keepalive for websocket - need more time if enabled?  Enable if not enabled.  Same with TCP if using TCP sockets.
2) Need to update gorilla websocket library?
3) Something specific to network or server?  Packet dump may show what is happening.

**Comment by m0netize** [comment] 2020-01-21 07:50
Not sure if this applies in your case, but we've been using wamp for our project and ran into a similar problem. It turned out to be Cloudflare dropping idle websockets after 60 seconds (I think it was 60 seconds). I believe this is documented Cloudflare behavior. We added a ping in our clients to fix it.

**Comment by gammazero** [comment] 2020-10-31 22:16
Keep alive can now be configured for client as well as server.  It is off by default, so enabling it may solve this issue.  Generally it is enabled on only the server (router), but you can configure it for client as well now, as of v3.0.1.

**Comment by gammazero** [comment] 2020-11-29 08:10
Looks like this issue can be remedied by use of websocket keepalives, either server, client, or both.  So, closing issue.

**Closed by gammazero** 2020-11-29 08:10 UTC
