### ISSUE TITLE
how is the performance under high concurrence?

### ISSUE THREAD

**Issue by BenDerPan** [gammazero/nexus#69] opened 2018-01-22 08:28 UTC
When I use nexus as a web service backend, some times ,it will throw an exception like session error,I registered a function may run for a minute, called it under a concurrence situation.

**Comment by gammazero** [comment] 2018-01-25 22:04
With high concurrence, do you mean that a router is:
1. serving a few messages to a large number of clients
2. serving a large number of messages to a few clients
3. serving a large number of messages to a large number of clients?

The answer, and the best way for me to investigate, may depend on what is being scaled up.  If you can give me a summary of what you are setup looks like, I will put together some test to reproduce this issue so it can  be fixed.

**Comment by gammazero** [comment] 2018-01-27 03:07
Added some basic pub/sub benchmarks, with up to 512 subscribers.  You can run like this:
```
cd aat
go test -run=XXX -bench=.
go test -run=XXX -bench=. -scheme=ws
go test -run=XXX -bench=. -scheme=wss
go test -run=XXX -bench=. -scheme=tcp
go test -run=XXX -bench=. -scheme=tcps
```
See if that has any problems.

I am adding additional tests for log-running RPC methods, and will see if I can find anything there.

**Comment by BenDerPan** [comment] 2018-01-27 06:20
I have a callee written in python, and a router with nexus, caller written in js(the web side),callee method is a long running function, there are two question:
1.when more than 1 caller call it , callee site  will process it in a blocked way, not  async way. 
2.when the callee returned a long string result , the session error happend, I search on the issues, may be it's the  problem of segment size(max size65535),but I am not sure how to fix it.
forgive my terrible english, thanks.

**Comment by gammazero** [comment] 2018-01-31 03:11
Thank you for the details.  I will set up my tests as close as possible to your setup.

A possible solution to help with large results is to divide them into chunks and have the callee return progressive call results.  The nexus router and [client](https://godoc.org/github.com/gammazero/nexus/client#Client.CallProgress) support this, and clients like [crossbar.io autobahn](https://crossbar.io/autobahn/) client also support this.  These examples show using progressive call results with autobahn python client with nexus router:
https://github.com/gammazero/nexus/tree/master/examples/interop/autobahn-python

I will let you know when I have tests running so we can compare notes.

**Comment by BenDerPan** [comment] 2018-02-01 04:15
@gammazero thanks,I will try the example.

**Comment by gammazero** [comment] 2018-05-15 05:56
The behavior under high concurrency is primarily dependent on the implementation of the clients.  The nexus router simply routes invocations to the appropriate callees. If large numbers of invocations are handled by the same callee, then these are all sent.  It is up to the callee implementation to handle the invocations concurrently or not, and send the results back to the router.  The router then routes the results back to the appropriate caller. The callee client can handle as many long-duration calls as it wants concurrently, or choose to process a limited number of them (maybe even only one).  This does not affect the router, which processes the results whenever it gets them.

A single caller client/session instance will process a call synchronously, waiting for the response to a call.  However, application can create as many caller sessions as it wants and they can all concurrently send call messages to the router, which are then delivered to the callee(s) as invocations.  Long-duration calls will cause an individual session to wait, but will not block others.

The router is designed so that it is not the limiting factor in concurrency/scaling, up to the limits of the resources of the host machine.

Hopefully this answers your question. I am going to close this issue, but if you have a more specific issue/question then you can always open another issue.

**Closed by gammazero** 2018-05-15 05:56 UTC
