### ISSUE TITLE
Compatibility between Autobahn-Java and Nexus

### ISSUE THREAD

**Issue by jurjen96** [gammazero/nexus#143] opened 2018-08-08 11:19 UTC
We are currently trying to implement a wamp connection between Autobahn-Java and the Nexus router. When we try to connect to the router, we get, after 5 seconds, the error that a timeout occurred:

`2018/08/08 12:19:10 Error attaching to router: did not receive HELLO: timeout waiting for message`

A code snippet for connecting to the router:

```
private void onJoinCallback(Session wamp_session, SessionDetails details){
        System.out.println("Successfully connected to Realm");
}

public void connect(){
        session.addOnJoinListener(this::onJoinCallback);
        client = new Client(session, address, realm);
        CompletableFuture<ExitInfo> exitInfoCompletableFuture = client.connect();
}
```

We also tried to connect to the router of Crossbar, and we got a successful connection between the session and realm. Do you know if Autobahn-Java is compatible with the Nexus router?

**Comment by robfra31** [comment] 2018-08-09 09:28
Hello, 
I have the same issue on Autobahn-Cpp, the connect method doesn't get any return.
      _transport = std::make_shared<autobahn::wamp_tcp_transport> (_io_service, iter->endpoint(), true);  
      _session = std::make_shared<autobahn::wamp_session>(_io_service, true);
      _transport->attach(std::static_pointer_cast<autobahn::wamp_transport_handler>(_session));
      _transport->connect().then([&](boost::future<void> connected)

**Comment by gammazero** [comment] 2018-08-09 09:42
This may have been the same issue, with how the Autobahn demos operate, addressed here:
https://github.com/gammazero/nexus/issues/93#issuecomment-386921746

**Comment by robfra31** [comment] 2018-08-09 09:51
I don't think because I am not using docker. It's a code that I compiled on my own without using autobahn examples.
Can I send to you the .exe that I produced to test with it ?
It's a simple process which tries to connect to the nexus router by giving him the server address and the realm name.

**Comment by gammazero** [comment] 2018-08-09 09:53
Not sure I will be able to run an exe, unless it is built for linux, freebsd, or mac.  May be better if I can get a small piece of code that exhibits and build that.

**Comment by gammazero** [comment] 2018-08-09 09:55
Also, if you enable debug in the router, does it log anything at all?  This would indicate if the client was at least able to connect.

**Comment by robfra31** [comment] 2018-08-09 10:02
I enabled the debug and I don't see anything. It's like if no one is communicating.
I've produced the same program for linux if you want to try it.
Because if I give the code, you will need to install lot of dependencies for autobahn-cpp..

**Comment by jurjen96** [comment] 2018-08-09 10:03
Same also applies for us, when we ran our code, we didn't use the example code of Autobahn-Java. By the way, we are running the Java code in Android.

> Also, if you enable debug in the router, does it log anything at all? This would indicate if the client was at least able to connect.

When we enable debug in the router, we see with our Android Java code only the Hello timeout waiting for message error. When we use the example code in a Java application, we get the following response from the Nexus router:
`2018/08/09 11:59:36 Error attaching to router: did not receive HELLO: receive channel closed`
And on the client side:
`Aug 09, 2018 11:59:33 AM io.crossbar.autobahn.wamp.transports.NettyWebSocketClientHandler
INFO: WebSocket Client disconnected!
Aug 09, 2018 11:59:33 AM ExampleClient onDisconnectCallback
INFO: Session with ID=0, disconnected.`

**Comment by gammazero** [comment] 2018-08-09 10:28
@jurjen96 If you are using the Autobahn docker demos, pease check if this is the problem: https://github.com/gammazero/nexus/issues/93#issuecomment-386921746

I have tested with the Autobahn Java client and it does work.  If your problem is the the above, them please give me more information about how you are connecting things:
- What transport are you using Websocket,  RawSocket (TCP, Unix)?
- What interface:port is server listening on, client connecting to (ipv6-v4 used)?
- Using TLS?

**Comment by gammazero** [comment] 2018-08-09 10:57
@jurjen96 I appears that your client is connecting, but then disconnects before sending HELLO to router.  Are you setting WebsocketServer.KeepAlive to a non-zero value?  I am wondering is websocket ping/pong could possibly be a problem

**Comment by jurjen96** [comment] 2018-08-09 12:00
Thanks for your quick response! For the example of Autobahn Java we didn't use the docker version, but we copied it to a Java application because we had some difficulties running their docker version. For the example of Autobahn Java we configured the router to use port 8080, but we still get "receive channel closed". 

> What transport are you using Websocket, RawSocket (TCP, Unix)?

For both the example and Android version we use Websocket transports

> What interface:port is server listening on, client connecting to (ipv6-v4 used)?

We use our local network address 192.168.0.x and port 8080. Our client is also on our local network.

> Using TLS?

No

> Are you setting WebsocketServer.KeepAlive to a non-zero value?

That is correct, we set the keepalive to 5 seconds to detect if one of our clients disconnects. When we set the keepalive parameter to 0, the error of "timeout waiting for message" still persists.

**Comment by gammazero** [comment] 2018-08-09 12:25
@jurjen96 This may be the answer you are looking for: https://groups.google.com/forum/#!topic/autobahnws/cLMj0bQcfxU

**Comment by jurjen96** [comment] 2018-08-09 12:41
Thanks, the person that started that topic is a colleague of mine ;) He is trying to get the example up and running while I try to implement it in our product which uses Android.

**Comment by robfra31** [comment] 2018-08-09 13:38
Okay so I tested the basics and I had a mistake on my configuration.
But now I have the following connection error:
From Nexus:

2018/08/09 15:35:11 New client sent: HELLO: &{Realm:nexus.realm1 Details:map[authid: authmethods:[] roles:map[caller:map[features:map[call_timeout:true]] subscriber:map[] publisher:map[] callee:map[features:map[call_timeout:true]]]]}
2018/08/09 15:35:11 Aborting client connection: no authentication supplied
2018/08/09 15:35:11 Error attaching to router: authentication error: no authentication supplied

From Autobahn-Cpp:
RawSocket handshake reply received
connect successful: valid handshake
RX preparing to receive message ..
5
Connected
session started
TX message (131 octets) ...
TX message: hello ["nexus.realm1", {"authid":"", "authmethods":[], "roles":{"sub
scriber":{}, "publisher":{}, "callee":{"features":{"call_timeout":true}}, "calle
r":{"features":{"call_timeout":true}}}}]
RX message (70 octets) ...
RX message received.
RX message: abort [{"error":"no authentication supplied"}, "wamp.error.authentic
ation_failed"]
RX preparing to receive message ..
FFailed to connectailed to join the realm :
wamp.error.authentication_failed

My configuration file of the server is:
{
    "websocket": {
        "address": ":8081",
        "cert_file": "",
        "key_file": "",
        "enable_compression": false,
        "allow_origins": ["*"]
    },
    "rawsocket": {
        "tcp_address": ":8080",
        "tcp_keepalive_interval": 180,
        "unix_address": "",
        "max_msg_len": 0,
        "cert_file": "",
        "key_file": ""
    },
    "log_path": "",
    "router": {
        "realms": [
            {
                "uri": "nexus.realm1",
                "strict_uri": false,
                "allow_disclose": true,
                "anonymous_auth": true,
                "meta_strict": false,
                "meta_include_session_details": [],
                "enable_meta_kill": false,
                "enable_meta_modify": false
            }
        ],
        "debug": true
    }
}

Do you have any idea of the problem ?

**Comment by jurjen96** [comment] 2018-08-09 14:08
I totally forgot to attach the output we got from the client, sorry about that. Might be helpfull:

```
W/art: Method processed more than once: boolean io.crossbar.autobahn.websocket.WebSocketReader.processHandshake()
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
                  at io.crossbar.autobahn.wamp.transports.AndroidWebSocket.initializeSerializer(AndroidWebSocket.java:160)
W/System.err:     at io.crossbar.autobahn.wamp.transports.AndroidWebSocket.access$100(AndroidWebSocket.java:32)
                  at io.crossbar.autobahn.wamp.transports.AndroidWebSocket$1.onConnect(AndroidWebSocket.java:86)
                  at io.crossbar.autobahn.websocket.WebSocketConnection$2.handleMessage(WebSocketConnection.java:648)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:148)
                  at android.app.ActivityThread.main(ActivityThread.java:5509)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)
```

I also tried to use the configs of robfra31, but I still received the timeout waiting for message error.

**Comment by gammazero** [comment] 2018-08-09 15:01
@robfra31 Notice that `authmethods:[]` is empty.  This means that your router does not have any way to authenticate the client.  You need to enable `AnonymousAuth` like this:
https://github.com/gammazero/nexus/blob/master/examples/simple/server.go#L24

Or, your router implementation needs to map the names of authmethods to authenticator implementations, like this:
https://github.com/gammazero/nexus/blob/master/aat/main_test.go#L127

**Comment by gammazero** [comment] 2018-08-09 15:10
@robfra31 OK, looks like you do have `"anonymous_auth": true,`.  Let me see what it is not picking this up..

**Comment by robfra31** [comment] 2018-08-09 15:12
I have added an authentification in the join method of autobahn-Cpp:
`_session->join(_realm, authmethods, authid).then([&](boost::future<uint64_t> joined)`
Now it can connect !
But after that, the servers says:
`2018/08/09 16:09:47 New client sent: HELLO: &{Realm:nexus.realm1 Details:map[authid:daemon authmethods:[wampcra] roles:map[subscriber:map[] publisher:map[] callee:map[features:map[call_timeout:true]] caller:map[features:map[call_timeout:true]]]]}
2018/08/09 16:09:47 Aborting client connection: could not authenticate with any method
2018/08/09 16:09:47 Error attaching to router: authentication error: could not authenticate with any method`

**Comment by gammazero** [comment] 2018-08-09 15:26
Right, because there is no authenticator for `wampcra`.

I think I see the problem.  You client provides an `authmethods` in its HELLO message, but that authmethods is empty.  The nexus code is no adding the anonymous authmethod if authmethods is defined, even if it is empty:
https://github.com/gammazero/nexus/blob/master/router/realm.go#L645

The code in the link above needs to change to:
```
if am, ok := details["authmethods"]; !ok || len(am) == 0 {
```

**Comment by robfra31** [comment] 2018-08-09 15:33
Error in compilation:
`..\router\realm.go:634:49: invalid argument am (type interface {}) for len`

**Comment by gammazero** [comment] 2018-08-09 15:34
Sorry, code should be this:
```
if am, _ := wamp.AsList(details["authmethods"]); len(am) == 0 {
```

**Comment by gammazero** [comment] 2018-08-09 15:47
I was able to make my client add an empty authmethods list, and was able to reproduce what you are seeing.  The code above fixes that.  I will PR that unless there are additional issues that need to be addresses.

**Comment by gammazero** [comment] 2018-08-10 06:04
@jurjen96 If the merged PR does not help you, then I will open a new issue for autobahn java running on Android.

@robfra31 If the merged PR fixes your problem, please let me know and I will close the issue.

**Comment by jurjen96** [comment] 2018-08-10 08:00
@gammazero  The merged PR did not fix the issue for us. Nonetheless, thanks for the effort you put into this issue!

**Comment by robfra31** [comment] 2018-08-10 13:52
Hello, it's okay the issue is fixed with your modification !
Thank you very much !

**Comment by gammazero** [comment] 2018-08-11 07:04
@jurjen96 I am closing this issue, and have opened a new issue to track the problem you are seeing: #146

**Closed by gammazero** 2018-08-11 07:04 UTC
