### ISSUE TITLE
Bytes and string both get encoded as strings

### ISSUE THREAD

**Issue by dionytadema** [gammazero/nexus#214] opened 2020-01-07 15:50 UTC
after updating to nexus 3.0.0 i can no longer send bytes via msgpack with autobahn python clients, they end up as a string and may cause the client to throw a protocol error and disconnect if the bytes contain invalid utf-8

i've tested these 2 components with both version 3.0.0 and version 2.1.1 (our current production)
**backend:**
```
from autobahn.twisted.component import Component, run

def main(session, details):
    def teststr():
        return 'bytes'

    def testuni():
        return u'string'

    session.register(teststr, u'test.str')
    session.register(testuni, u'test.uni')

# Create wamp conn
server = Component(
    transports=[{
        'url': u'ws://localhost:9000',
        'serializers': ['msgpack']
    }],
    realm=u'rie.cloudmanager',
)
server.on_join(main)

if __name__ == "__main__":
    run([server])
```
**client:**
```
from autobahn.twisted.component import Component, run
from twisted.internet.defer import inlineCallbacks

@inlineCallbacks
def main(sess, details):
    str = yield sess.call(u'test.str')
    print type(str)
    uni = yield sess.call(u'test.uni')
    print type(uni)
    print('Done')

client = Component(
    transports=[{
        'url': u'ws://localhost:9000',
        'serializers': ['msgpack']
    }],
    realm=u'test',
)
client.on_join(main)

if __name__ == '__main__':
    run([client])
```

I expected both versions to output:
```
2020-01-07T16:36:23+0100 <type 'str'>
2020-01-07T16:36:23+0100 <type 'unicode'>
2020-01-07T16:36:23+0100 Done
```
however when run with version 3.0.0 of the router we see that both string and bytes get returned as the same type to the callee:
```
2020-01-07T16:41:07+0100 <type 'unicode'>
2020-01-07T16:41:07+0100 <type 'unicode'>
2020-01-07T16:41:07+0100 Done
```

**Comment by martin31821** [comment] 2020-01-14 11:07
Are you able to do a pcap/tcpdump/wireshark so we can see, how your wire data looks like?

**Comment by dionytadema** [comment] 2020-01-21 10:44
sorry for the late reply, i was on vacation for a week

i'll see if i can see what the router is sending so we can pin down where the problem lies

**Comment by dionytadema** [comment] 2020-01-21 13:20
alright i figured out how wireshark works again

send by backend:
result from test.str():
```
95 30 01 80 a8 74 65 73 74 2e 73 74 72 91 c4 01 61
```
result from test.uni():
```
95 30 02 80 a8 74 65 73 74 2e 75 6e 69 91 a1 75
```

**Comment by martin31821** [comment] 2020-01-21 13:52
at this point, I think it's a problem with autobahn|python. I just used the msgpack bytes you provided, threw them into https://kawanet.github.io/msgpack-lite/ to decode/transcode into JSON and I see the following:

test.str() gets encoded as Object of type 'Buffer' with a single data item (97)
whereas test.uni() gets encoded correctly as string with content "u"

In both cases, the message you provided is the 'CALL' direction, which means that this packet did not pass the router at this point. To conclude, I think something in autobahn|python or your code is broken, but I can't tell you exactly what.

**Comment by dionytadema** [comment] 2020-01-21 14:28
sorry, i was still editing that message, i found the correct packages:

when ran agains the 3.0.0 version i get the folowing websocket packages
backend sends yield, 'bytes' as binary (05 is the length)
`94 46 cd 01 57 80 91 c4 05 62 79 74 65 73`
router sends result, 'bytes' as fixed lenght string (a5)
`94 32 01 80 91 a5 62 79 74 65 73`
so clearly the router changes the encoding

**Comment by dionytadema** [comment] 2020-01-21 14:30
if you want to inspect for yourself check this wireshark dump

[msgpack.pcapng.gz](https://github.com/gammazero/nexus/files/4091493/msgpack.pcapng.gz)

anyways i'm sure it's something to do with nexus, as the exact same python code works fine when connecting to a 2.x version in the same environment and breaks with a 3.0.0 router

**Comment by martin31821** [comment] 2020-01-21 14:45
Using the pcapng, I can indeed confirm that nexusd is converting the buffer into a string during processing the message.

**Comment by dionytadema** [comment] 2020-01-21 15:02
we don't use much config, as we run the router from within a go application

it's started like this:
```
func main() {
	// Load Config and resolve public ip.
	config := go_util.LoadConfig()
	ws_address := config.Domain + ":9000"
	wss_address := config.Domain + ":9001"

	// Create router instance.
	routerConfig := &router.Config{
		RealmConfigs: []*router.RealmConfig{
			&router.RealmConfig{
				URI:           wamp.URI("rie.cloudmanager"),
				AnonymousAuth: true,
			},
		},
	}
	nxr, err := router.NewRouter(routerConfig, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer nxr.Close()
```
other than that we just set the websocket timeout on the server but that shouldn't have anything to do with it

might it be something with the dependancies?
my go mod file specifies:
```
module gitlab.interactive-robotics.com/RIE2/core

go 1.13

require (
	github.com/Microsoft/go-winio v0.4.7 // indirect
	github.com/capnm/sysinfo v0.0.0-20130621111458-5909a53897f3
	github.com/docker/distribution v2.6.2+incompatible // indirect
	github.com/docker/docker v1.13.2-0.20170524085120-eef6495eddab
	github.com/docker/go-connections v0.3.0 // indirect
	github.com/docker/go-units v0.3.3 // indirect
	github.com/gammazero/nexus/v3 v3.0.0
	github.com/go-stack/stack v1.7.0 // indirect
	github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db // indirect
	github.com/google/go-cmp v0.3.1 // indirect
	github.com/mongodb/mongo-go-driver v0.0.16
	github.com/pkg/errors v0.8.0 // indirect
	github.com/stevvooe/resumable v0.0.0-20180830230917-22b14a53ba50 // indirect
	github.com/stretchr/testify v1.4.0 // indirect
	github.com/tidwall/pretty v1.0.0 // indirect
	github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c // indirect
	github.com/xdg/stringprep v1.0.0 // indirect
)
```

**Comment by martin31821** [comment] 2020-01-21 15:50
I managed to reproduce it within nexusd, so it's definitely a problem with the ugorji/go package. 
As a workaround (if you're dealing with binary data) I suggest you to register a msgpack extension and use this for binaryData.

**Comment by dionytadema** [comment] 2020-01-21 16:01
hm alright, thanks for looking into it

i'll revert to version 2.1.3 for now as that sounds like less work (our deployment for the clients is quite convoluted)

**Comment by dionytadema** [comment] 2020-01-21 23:31
It may be fixed by this pull request, let's hope it gets merged soon

https://github.com/ugorji/go/pull/327

**Comment by gammazero** [comment] 2020-03-10 00:07
I will update to latest ugorji package

**Comment by dionytadema** [comment] 2020-05-08 08:33
seems like ugorji has stopped maintaining his repos so i doubt that PR will ever be merged

**Comment by Lois31** [comment] 2020-06-02 07:33
Hello, 
We are having exactly the same problem. When transmitting data of type bytes, we recieve data of type string. 
I tested with the crossbar router and everything is working properly. 
If the ugorji package is no longer maintained and it poses a problem, do you plan to replace it in the implementation of Nexus? If yes, on what horizon?
Thanks.

**Comment by Lois31** [comment] 2020-06-03 06:53
I tried the v2.1.1 version of Nexus, as indicated at the beginning of this ticket, however I still get the same result...
The problem is present in versions v2.1.1, v2.1.3, v3.0.0.

Below my configuration and my test:

- Python3.8
- autobahn 20.4.3
- msgpack 1.0.0
- Nexus 3.0.0

Below an example allowing to highlight the problem:

**Backend.py**
```
import asyncio
from autobahn.asyncio.wamp import ApplicationSession
from autobahn.asyncio.component import Component, run

class Backend(ApplicationSession):
    def __init__(self, config=None):
        config.realm = 'TESTS'
        super().__init__(config)


    async def onJoin(self, details):
        print('Register test_echo_payload')
        await self.register(self.test_echo_payload, 'test.echo.payload')

    async def onDisconnect(self):
        loop  = asyncio.get_event_loop()
        loop.stop()


    async def test_echo_payload(self, value: bytes) -> bytes:
        if not isinstance(value, bytes):
            print('Value is not an instance of bytes but is a %s' % (type(value)))
        return value


if __name__ == '__main__':
    backend = Component(
            session_factory = Backend,
            transports      = [
                {
                    'type':        'websocket',
                    'serializers': ['msgpack'],
                    'url':         'ws://localhost:8902/ws',
                    'max_retries': 3
                }
            ]
        )

    run([backend])
```

**Client.py**
```
import asyncio
from autobahn.asyncio.wamp import ApplicationSession
from autobahn.asyncio.component import Component, run


class Client(ApplicationSession):
    def __init__(self, config=None):
        config.realm = 'TESTS'
        super().__init__(config)


    async def onJoin(self, details):
        print('Call test_echo_payload')
        loop = asyncio.get_running_loop()
        loop.create_task(self.test_echo_payload())

    async def onDisconnect(self):
        loop  = asyncio.get_event_loop()
        loop.stop()

    async def test_echo_payload(self):
        message_bytes = b'\x01\x02\x03\x04\x05\x06\x07\x08\x09\x10'
        ret = await self.call('test.echo.payload', message_bytes)


if __name__ == '__main__':
    client = Component(
            session_factory = Client,
            transports      = [
                {
                    'type':        'websocket',
                    'serializers': ['msgpack'],
                    'url':         'ws://localhost:8902/ws',
                    'max_retries': 3
                }
            ]
        )

    run([client])
```
Here are the steps of my test:

1. Start the Nexus router on Linux1 machine
2. Star the Backend component on Linux2 machine
3. Start the Client component on Linux1 machine

The Client component correctly sends the byte table type message encoded in msgpack as follows:
`0x9530ce0001e24080b1746573742e6563686f2e7061796c6f616491c40a01020304050607080910`
But on the Backend component, we receive the message of the following form:
```
0000   18 60 24 80 ee d2 48 0f cf 35 d8 ac 08 00 45 00   .`$...H..5....E.
0010   00 76 8a 82 40 00 40 06 8c 66 2c 21 66 b9 2c 21   .v..@.@..f,!f.,!
0020   64 9e 22 c6 c0 e8 76 98 54 58 13 f5 16 52 80 18   d."...v.TX...R..
0030   00 85 b0 f0 00 00 01 01 08 0a 10 8f 32 63 7a ec   ............2cz.
0040   34 1c 82 40 95 44 19 12 81 a9 70 72 6f 63 65 64   4..@.D....proced
0050   75 72 65 b1 74 65 73 74 2e 65 63 68 6f 2e 70 61   ure.test.echo.pa
0060   79 6c 6f 61 64 91 bd 5b 22 5c 75 30 30 30 30 62   yload..["\u0000b
0070   27 41 51 49 44 42 41 55 47 42 77 67 4a 45 41 3d   'AQIDBAUGBwgJEA=
0080   3d 27 22 5d                                       ='"]
```

**Comment by Lois31** [comment] 2020-11-23 10:45
Hello gammazero,

Have you had time to spend some time on this issue ?
Currently, in order to send payloads, we must modify the payload before each send and at each reception...
Those which decrease performance and complicate the exchange of data between languages. What goes against WAMP technology ...

Thank you in advance for your return

**Comment by gammazero** [comment] 2020-11-23 18:52
@Lois31 I was hoping this was resolved by updates to codec dependencies, but apparently that has not been the case.  I will spend time this week to resolve this as it looks like a bigger problem than I thought.  Rewriting payloads is a terribly way to suffer. Let me see what can be done.

**Comment by gammazero** [comment] 2020-11-26 12:28
@Lois31 The problem came from msgpack being configured to decode raw bytes into strings.  When the router decoded a msgpack message containing raw bytes, those bytes were into a string.  When this data was sent out to destination client, it was then re-encoded as a string and no longer as bytes.  This caused clients expecting bytes to get a string unexpectedly.

This is fixed by using the new msgpack spec and disabling the option to convert raw bytes to string.  Fixed by PR #232 

The PR also includes a unit test to check that the fix works as well as additional autobahn python clients that demonstrate the case you provided in this issue is working.

Please see if this fixes the issue for you, and close the issue if it looks good. I will include this fix in a new release.

**Comment by gammazero** [comment] 2020-11-29 08:16
@Lois31 The latest release v3.0.2 includes the fix for this issue, and unit tests to demonstrate.

**Comment by Lois31** [comment] 2020-11-30 09:58
@gammazero I don't see the v3.0.2 release into https://github.com/gammazero/nexus/tags ...

**Comment by gammazero** [comment] 2020-11-30 11:21
@Lois31 Sorry, that is v3.0.3 which is now available.

**Comment by Lois31** [comment] 2020-11-30 12:54
I just tested and it works!
Thank you very much for this correction.

**Comment by gammazero** [comment] 2020-11-30 17:10
Thank you @Lois31 for confirming this.  Closing issue.

**Closed by gammazero** 2020-11-30 17:10 UTC
