### ISSUE TITLE
Data race when publishing struct reference

### ISSUE THREAD

**Issue by camohob** [gammazero/nexus#212] opened 2019-12-03 12:13 UTC
https://github.com/gammazero/nexus/blob/96d8c237ee8727b31fbebe0074d5cfec3f7b8a81/transport/websocketpeer.go#L187

When i use `client.Publish()` with struct reference and then change this struct - i have data race coditions, because `websocketpeer.sendHandler()` works from goroutine.

**Comment by gammazero** [comment] 2019-12-07 02:08
Been holding off fixing this as it fixed in an unpublished PR to handle message queueing outbound messages in router.  Will fix soon (target Dec. 8) if PR is not ready.

**Comment by gammazero** [comment] 2020-10-31 18:12
A number of fixes have been made since this issue was filed, but I am not sure if your issue has been addressed.  Please tell me what structure you are seeing a race in so that I can determine if this is something that needs to be copied or synchronized (or is even a problem anymore).

**Comment by gammazero** [comment] 2020-11-18 15:32
@camohob I cannot find how to reproduce this issue.  There should not be any data race with intended use of the API.  If this is still a problem then please reopen this issue and provide information on how to reproduce what you are seeing.

**Closed by gammazero** 2020-11-18 15:32 UTC
