### ISSUE TITLE
Empty list/dict is omitted

### ISSUE THREAD

**Issue by azamat-sharapov** [gammazero/nexus#166] opened 2019-02-14 16:57 UTC
When returning empty `Args` or `Kwargs` in InvokeResults from RPC InvocationHandler, nexus omits that field. But in my use case, I would like empty JSON array/object, instead of omitting it. Looking at source, I think it's caused because of `wamp:"omitempty"` tags. Is there way to work it around?

**Comment by gammazero** [comment] 2019-04-06 23:50
That was done to minimize what needed to be serialized.  Is this causing a compatibility issue with another WAMP implementation?  If needed, that could be configurable behavior in the serializer.  I want to make sure I understand the need; is this a preference for your use case or is there a bigger interoperability issue that needs to be addressed?

**Comment by azamat-sharapov** [comment] 2019-04-08 06:57
> That was done to minimize what needed to be serialized

This makes sense.

> is this a preference for your use case

Yes.
I'm using nexus as server and client is on browser (javascript). I wanted to avoid extra checks for existence of args/kwargs on frontend and assume that nexus returns empty array/object (e.g. _empty_ slice given as `Args`, not _nil_ slice).

If you think it is worth omitting empty fields for performance, I agree and can workaround it on client side, instead of server.

**Comment by martin31821** [comment] 2019-04-08 06:59
Most client libraries should replace omitted values by empty arrays/objects anyway. Which client are you using?

**Comment by azamat-sharapov** [comment] 2019-04-08 07:01
@martin31821 I'm using https://github.com/KSDaemon/wampy.js

**Comment by gammazero** [comment] 2019-07-08 00:12
Closing issue as "by design".  Empty fields are omitted for performance.  Client should check for existence of fields.

**Closed by gammazero** 2019-07-08 00:12 UTC
