### ISSUE TITLE
wamp.error.network_failure

### ISSUE THREAD

**Issue by HollowTooth** [gammazero/nexus#105] opened 2018-06-07 08:23 UTC
Hello again :)

I'm trying to troubleshoot the error `wamp.error.network_failure`. I was just wondering, what exactly causes this error to appear. Does this imply a limitation on resources (network too crowded), or is there a problem with a client not responding ? (this error mostly appears after every RPC call I make to a nexus client (from AutobahnJS frontend). I have quite a lot of nodes connected to the router, and most of them are not on the local network. 

According to the WAMP RPC draft, the router is encountering a network failure. My question is only, what are these network failures :)

**Comment by gammazero** [comment] 2018-06-07 19:21
This error happens when the _callee_ client is not handling RPC requests.  The code where this happens is here: https://github.com/gammazero/nexus/blob/master/router/dealer.go#L639

The nexus router maintains a small outbound channel, per client, which should be sufficient to handle bursts of messages to each client.  However, if a client is handling requests slowly, or not at all, and there are enough requests that the IPC (websocket) send buffer is filled so that the websocket cannot buffer any more messages, and the client's outbound channel becomes full, then the router will drop the message.   This is indicated by an error that gets logged as well as is returned to the caller.

If your callee client is operating correctly, but is too slow for the number of incoming requests, there are a few options to remedy this:
- Handle the RPC requests in parallel.  If the requests can be handled independently, then handle each in a separate goroutine/thread/precess (depending on language client is written in).  That way a new request does not need to wait for all the previous requests to finish.  If your callee is a using the nexus client, I can provide examples for this if helpful.
- Have additional clients register to handle the same procedure, using shared registration.  The round-robin handling policy provides a way to load-balance the RPC requests over all the callees.  This is very useful for having RPC handlers (callees) distributed across different machines.
- Determine if your callee has a resource bottleneck, like a slow database or other backend resource.  If this is a shared resource, then increasing the number of goroutines or threads or clients will not help and this will need to be fixed to meet your scaling needs.
 
If the problem is simply that there is a burst of messages so large that they cannot all be sent to a client in time, no matter how capable the client is, then I can make some changes to allow the router to buffer more messages.  However, that is more likely only hide the problem you are experiencing, and not fix it.

**Comment by gammazero** [comment] 2018-06-09 04:06
Hello @HollowTooth,

Checking to see if you have any more information on the problem you were experiencing.  If there is some testing I can do to make sure there is not a problem with nexus, or with the way nexus interacts with specific clients, please let me know.

**Comment by gammazero** [comment] 2018-06-14 01:52
I am looking to see what kind of client-side improvements can be made regarding concurrency, and was thinking more about this issue.  One thing that may cause your RPC it is if your client is receiving events that is has subscribed to, and these events are not being handled.  The client will block processing additional incoming messages, such as RPC requests, waiting for an event to be handled (user-defined event handler to return).

I am considering such things as offloading the events to a separate goroutine that dispatches the events (calls the user-defined handler).  As long as the channel to the event dispatcher does not fill up, this will allow the client to handle other messages without waiting for the event handler to finish.  There is not really a correct size for this channel, so it is not guaranteed to eliminate the problem.

Another thought is to provide a version of `Subscribe` that takes a channel instead of a handler function. If the caller needs to preserve event ordering across different subscriptions, then they can provide an unbuffered channel for each subscription and select across all channels.  Otherwise, they can supply a buffered channel and the client can put the event in the channel without necessarily having to wait.

**Comment by HollowTooth** [comment] 2018-06-14 11:59
Hi :)

Regarding the issue, the problem was purely on my end. You last comment about handling events recieved, and an event blocking the goroutine was the cause of the problem indeed. Although your idea, to have a offhandling channel has it's pluses, the size of said channel would have to be predefined.

In my case, the problem was an "accidental" infinite loop regarding some interfaces and a mathimatical equation, that did not break the loop correctly. However, I think even in the case, that the information you have to process takes a second, and you recieve let's say a spike of 5 messages (which would be blocked in the current version of nexus), can easily be handled client side with the use of other goroutines or even the end programmer making his own offhandling channel, and the subscription just offloads it's data into the channel. Soo I don't think, that offloading is really neccesary.

Again, thank you for the quick responses and I'm sorry it took a while for me to comment. If you want, I can close this issue as I've already discovered that the problem was on my end :)

**Comment by gammazero** [comment] 2018-06-14 14:04
Thank you for the feedback.  Since the current API already gives the caller the ability to do offloading themselves, nexus does not require changes.  As always, any suggestions for improving this WAMP implementation are very welcome.  Closing issue.

**Closed by gammazero** 2018-06-14 14:04 UTC
