### ISSUE TITLE
Doing an RPC call in an event listener callback hangs

### ISSUE THREAD

**Issue by siosphere** [gammazero/nexus#219] opened 2020-06-30 20:58 UTC
We were hooking up the subscription topic events, and when attempting to load subscription information in the callback, it would block until the context eventually timed out.

Running the RPC call in a go-routine alleviated the issue.

Hangs indefinitely or times out
```go
eventHandler := func(event *wamp.Event) {
    callArgs := wamp.List{event.Arguments[1]}
    result, err := client.Call(ctx, "wamp.subscription.get", nil, callArgs, nil, nil)
    if err != nil {
        log.Fatalf(err.Error())
    }
    log.Printf("%+v", result)
}
```

Works as expected
```go
eventHandler := func(event *wamp.Event) {
    go func() {
        callArgs := wamp.List{event.Arguments[1]}
        result, err := client.Call(ctx, "wamp.subscription.get", nil, callArgs, nil, nil)
        if err != nil {
            log.Fatalf(err.Error())
        }
        log.Printf("%+v", result)
    }()
}
```

I was a little surprised, considering the readme said it should all be non-blocking

**Comment by gammazero** [comment] 2020-10-31 03:25
The router is non-blocking in that no session will ever block another session, and blocked output from a session will not block input from the session.  The client is non-blocking in that different sessions will not block each other.  So, I likely need to take another pass at the documentation.

To explain the [expected] behavior above...
You cannot call a client function from within a callback.  Since the client is waiting for the event callback to return, it cannot process the router's response to the `Call`.  Therefore the `Call` times out waiting for the response that the client is not processing because the event handler has not returned.  The reason this is the case (why the event handler is not run asynchronously to the rest of the message processing) is explained here:
https://github.com/gammazero/nexus/blob/v3/client/client.go#L1085-L1087
WAMP protocol requires the event ordering.

So, this is easy to handle in a number of ways.
- Use a goroutine to call client functions from within an event handler.
- Use [SubscribeChan](https://godoc.org/github.com/gammazero/nexus/client#Client.SubscribeChan) to have events delivered on a channel instead of using an event handler callback. Of course the channel needs to be read from to keep processing events.
- Use some other signaling mechanism to allow your event handler to signal another goroutine to call `Call`.

OK, these are all just variations of the same solution.  The real fix is to make this clear about this behavior.

**Comment by gammazero** [comment] 2020-11-26 15:07
I have added a section on [Client Concurrency](https://github.com/gammazero/nexus/wiki/Client-Concurrency) to the documentation describing the above.

Since this is not a defect, but expected behavior, and docs have been amended to describe it better, I am closing this issue.  If you feels it was not sufficiently addressed, please reopen.

**Closed by gammazero** 2020-11-26 15:07 UTC
